### ISSUE TITLE
qPCR feature request

### ISSUE THREAD

**Issue by MiikoSokka** [JohnUrban/sciara-project-tools#1]
Relative efficiency plots for each primer pair combination (plot of delta-Ct against logTemplate).

**Comment by JohnUrban** [comment]
Get the latest commit: ```git pull origin master```

Look in manual-validation section of ```validation-plate-template.R``` near lines 107-121:
```
## Will look at all pairs NEXT in frt, BUT here is how to look at relative efficiency table for single target locus vs norm locus:
target <- "ARS1625"
norm <- "surr1"
rt1 <- relativeEfficiencyTable(normalizerAvgCts = subset(avgCtTable, primerPair == norm)$avgCt, targetAvgCts = subset(avgCtTable, primerPair == target)$avgCt, dilSeries = dilutionSeries(startingAmount, DF, numPoints, TRUE))
## Plot the dCTs over the dilSeries to see how it does in the rel eff test
rt1
relativeEfficiencyPlot(rt1)

## BEFORE calculating this -- FILL IN ABOVE VALUES
frt <- fullRelativeEfficiencyTable(avgCtTable=avgCtTable, normalizer=norm, startingAmount=startingAmount, dilutionFactor=DF, numPoints=numPoints, highToLow=TRUE)
frt
## To see all rel eff plots, make plottables=TRUE; can suppress FRT output with returnfrt=FALSE
fullRelativeEfficiencyTable(avgCtTable=avgCtTable, normalizer=norm, startingAmount=startingAmount, dilutionFactor=DF, numPoints=numPoints, highToLow=TRUE, returnfrt=FALSE, plottables=TRUE)
## ALSO: A Wrapper Function was made that does exactly the above without needing to specify the extra options:
allRelativeEfficiencyPlots(avgCtTable=avgCtTable, normalizer=norm, startingAmount=startingAmount, dilutionFactor=DF, numPoints=numPoints, highToLow=TRUE)
```

That shows an example of how to do it for a single pair or for all pairs given a specific normalizer. It is part of the manual validation process, but is not part of the fully automated validation process. Having sad that, I am not sure it should be since all the pairwise comparisons of all primer pairs to all normalizers (aka controls in the scripts) would generate an enormous amount of plots and get in the way of seeing some of the others. The fully automated part is mainly just for when you want the answer immediately rather than carefully going through it all manually.
